(ns clojureintro.core)

(load-file "src/clojureintro/video1.clj")

(println "\nBaking Cookies!\n")
(start-over)
(grab :egg)
(squeeze)
(add-to-bowl)
(grab :butter)
(add-to-bowl)
(grab :cup)
(scoop :flour)
(add-to-bowl)
(scoop :sugar)
(add-to-bowl)
(release)
(mix)
(pour-into-pan)
(bake-pan 30)
(cool-pan)
(status)

(println "\nBaking a Cake!\n")
(start-over)
(grab :cup)
(scoop :flour)
(add-to-bowl)
(scoop :flour)
(add-to-bowl)
(release)
(grab :egg)
(squeeze)
(add-to-bowl)
(grab :egg)
(squeeze)
(add-to-bowl)
(grab :cup)
(scoop :milk)
(add-to-bowl)
(release)
(grab :cup)
(scoop :sugar)
(add-to-bowl)
(release)
(mix)
(pour-into-pan)
(bake-pan 25)
(cool-pan)
(status)


(defn add-egg [] (grab :egg) (squeeze) (add-to-bowl))
(defn add-sugar [] (grab :cup) (scoop :sugar) (add-to-bowl) (release))
(defn add-flour [] (grab :cup) (scoop :sugar) (add-to-bowl) (release))
(defn add-milk [] (grab :cup) (scoop :milk) (add-to-bowl) (release))
(defn add-butter [] (grab :butter) (add-to-bowl))
(status)
(add-egg)
(add-sugar)
(add-flour)
(add-milk)
(add-butter)
